version: '3.8'

services:
  postgres:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: in
      POSTGRES_PASSWORD: touch
      POSTGRES_DB: intouchdb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U in"]
      interval: 30s
      timeout: 5s
      retries: 5

  intouch:
    depends_on:
      postgres:
        condition: service_healthy
    build: .
    ports:
      - "5005:5005"
    environment:
      - DATABASE_URL=postgresql://in:touch@postgres:5432/intouchdb
      - SECRET_KEY=notouchy

volumes:
  postgres_data:
